-- FSS Invoice — PostgreSQL / Supabase schema (lowercase identifiers)
CREATE TABLE IF NOT EXISTS clientmaster (
    clientid          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientname        VARCHAR(200) NOT NULL UNIQUE,
    gstin             VARCHAR(20),
    address           VARCHAR(500),
    contactperson     VARCHAR(100),
    email             VARCHAR(150),
    mobile            VARCHAR(20),
    mhstate           SMALLINT NOT NULL DEFAULT 0,
    openingbalance    NUMERIC(18,2) NOT NULL DEFAULT 0,
    isactive          SMALLINT NOT NULL DEFAULT 1,
    createdat         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedat         TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS businesssegments (
    businesssegmentid   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    businesssegmentname VARCHAR(100) NOT NULL UNIQUE,
    segmentcode         VARCHAR(30),
    isactive            SMALLINT NOT NULL DEFAULT 1,
    sortorder           INTEGER NOT NULL DEFAULT 0,
    createdat           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS taxinvoices (
    invoiceid                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid                 INTEGER NOT NULL REFERENCES clientmaster(clientid),
    invoicenumber            VARCHAR(30) NOT NULL UNIQUE,
    invoicedate              DATE NOT NULL,
    taxableamount            NUMERIC(18,2) NOT NULL DEFAULT 0,
    cgstamount               NUMERIC(18,2) NOT NULL DEFAULT 0,
    sgstamount               NUMERIC(18,2) NOT NULL DEFAULT 0,
    igstamount               NUMERIC(18,2) NOT NULL DEFAULT 0,
    totalamount              NUMERIC(18,2) NOT NULL,
    supplytype               VARCHAR(50),
    pdfpath                  VARCHAR(500),
    excelpath                VARCHAR(500),
    createdby                VARCHAR(50),
    createdat                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    businesssegmentid        INTEGER REFERENCES businesssegments(businesssegmentid),
    duedate                  DATE,
    paymenttermsdays         INTEGER NOT NULL DEFAULT 30,
    invoicetype              VARCHAR(20) NOT NULL DEFAULT 'TAX',
    convertedfrominvoiceid   INTEGER
);
CREATE INDEX IF NOT EXISTS ix_taxinvoices_clientdate ON taxinvoices(clientid, invoicedate);

CREATE TABLE IF NOT EXISTS invoicelineitems (
    lineid        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoiceid     INTEGER NOT NULL REFERENCES taxinvoices(invoiceid) ON DELETE CASCADE,
    srno          INTEGER NOT NULL,
    particulars   VARCHAR(500) NOT NULL,
    workdate      DATE,
    amount        NUMERIC(18,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS receipts (
    receiptid              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid               INTEGER NOT NULL REFERENCES clientmaster(clientid),
    receiptnumber          VARCHAR(30) NOT NULL UNIQUE,
    receiptdate            DATE NOT NULL,
    amountreceived         NUMERIC(18,2) NOT NULL,
    paymentmode            VARCHAR(50) NOT NULL,
    referencenumber        VARCHAR(100),
    remarks                VARCHAR(500),
    createdby              VARCHAR(50),
    createdat              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    invoiceamount          NUMERIC(18,2),
    tdspercentage          NUMERIC(5,2) NOT NULL DEFAULT 0,
    tdsamount              NUMERIC(18,2) NOT NULL DEFAULT 0,
    financialyear          VARCHAR(10),
    tdscertificatereceived SMALLINT NOT NULL DEFAULT 0,
    tdscertificateno       VARCHAR(50),
    tdscertificatedate     DATE,
    taxableamount          NUMERIC(18,2),
    gstamount              NUMERIC(18,2) NOT NULL DEFAULT 0,
    gstpaidamount          NUMERIC(18,2) NOT NULL DEFAULT 0,
    gstpaidstatus          VARCHAR(20) DEFAULT 'unknown',
    tdsmanual              SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_receipts_clientdate ON receipts(clientid, receiptdate);

CREATE TABLE IF NOT EXISTS ledgersequence (
    seqname   VARCHAR(50) PRIMARY KEY,
    nextvalue INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS nongstbills (
    nongstbillid      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid          INTEGER NOT NULL REFERENCES clientmaster(clientid),
    billnumber        VARCHAR(30) NOT NULL UNIQUE,
    billdate          DATE NOT NULL,
    amount            NUMERIC(18,2) NOT NULL,
    description       VARCHAR(500) NOT NULL,
    businesssegmentid INTEGER REFERENCES businesssegments(businesssegmentid),
    remarks           VARCHAR(500),
    createdby         VARCHAR(50),
    createdat         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS receiptinvoiceallocations (
    allocationid      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiptid         INTEGER NOT NULL REFERENCES receipts(receiptid) ON DELETE CASCADE,
    invoiceid         INTEGER NOT NULL REFERENCES taxinvoices(invoiceid),
    businesssegmentid INTEGER NOT NULL REFERENCES businesssegments(businesssegmentid),
    allocatedamount   NUMERIC(18,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS receiptnongstallocations (
    allocationid      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receiptid         INTEGER NOT NULL REFERENCES receipts(receiptid) ON DELETE CASCADE,
    nongstbillid      INTEGER NOT NULL REFERENCES nongstbills(nongstbillid),
    businesssegmentid INTEGER NOT NULL REFERENCES businesssegments(businesssegmentid),
    allocatedamount   NUMERIC(18,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS expensecategories (
    expensecategoryid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoryname      VARCHAR(100) NOT NULL UNIQUE,
    isactive          SMALLINT NOT NULL DEFAULT 1,
    issystem          SMALLINT NOT NULL DEFAULT 0,
    createdat         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS expenses (
    expenseid           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expensedate         DATE NOT NULL,
    expensecategoryid   INTEGER NOT NULL REFERENCES expensecategories(expensecategoryid),
    expensedescription  VARCHAR(500) NOT NULL,
    amount              NUMERIC(18,2) NOT NULL,
    gstamount           NUMERIC(18,2) NOT NULL DEFAULT 0,
    totalamount         NUMERIC(18,2) GENERATED ALWAYS AS (amount + gstamount) STORED,
    vendorname          VARCHAR(200),
    paymentmode         VARCHAR(50),
    referencenumber     VARCHAR(100),
    remarks             VARCHAR(500),
    allocationtype      VARCHAR(30) NOT NULL DEFAULT 'segment',
    businesssegmentid   INTEGER REFERENCES businesssegments(businesssegmentid),
    createdby           VARCHAR(50),
    createdat           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedat           TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS expensesegmentallocations (
    allocationid      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expenseid         INTEGER NOT NULL REFERENCES expenses(expenseid) ON DELETE CASCADE,
    businesssegmentid INTEGER NOT NULL REFERENCES businesssegments(businesssegmentid),
    allocatedamount   NUMERIC(18,2) NOT NULL,
    allocpercent      NUMERIC(7,4)
);

CREATE TABLE IF NOT EXISTS reminderhistory (
    reminderid     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoiceid      INTEGER NOT NULL REFERENCES taxinvoices(invoiceid),
    clientid       INTEGER NOT NULL REFERENCES clientmaster(clientid),
    ruletype       VARCHAR(30) NOT NULL,
    channel        VARCHAR(20) NOT NULL DEFAULT 'email',
    sentat         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    recipient      VARCHAR(200) NOT NULL,
    deliverystatus VARCHAR(50) NOT NULL DEFAULT 'sent',
    messagebody    TEXT,
    createdby      VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS whatsapplog (
    logid       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid    INTEGER NOT NULL REFERENCES clientmaster(clientid),
    invoiceid   INTEGER,
    mobile      VARCHAR(20) NOT NULL,
    messagetype VARCHAR(30) NOT NULL,
    messagebody TEXT,
    sentat      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    sentby      VARCHAR(50),
    status      VARCHAR(50) NOT NULL DEFAULT 'initiated'
);

CREATE TABLE IF NOT EXISTS projectcosts (
    costid             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clientid           INTEGER NOT NULL REFERENCES clientmaster(clientid),
    projectname        VARCHAR(200) NOT NULL DEFAULT 'General',
    periodyear         INTEGER NOT NULL,
    periodmonth        INTEGER NOT NULL,
    revenue            NUMERIC(18,2) NOT NULL DEFAULT 0,
    consultancycharges NUMERIC(18,2) NOT NULL DEFAULT 0,
    manhours           NUMERIC(18,2) NOT NULL DEFAULT 0,
    employeecost       NUMERIC(18,2) NOT NULL DEFAULT 0,
    travelcost         NUMERIC(18,2) NOT NULL DEFAULT 0,
    miscellaneouscost  NUMERIC(18,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS auditlog (
    auditid    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(50) NOT NULL,
    action     VARCHAR(100) NOT NULL,
    entitytype VARCHAR(50),
    entityid   VARCHAR(50),
    details    TEXT,
    ipaddress  VARCHAR(50),
    createdat  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bankimportlog (
    importid     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename     VARCHAR(200) NOT NULL,
    bankdetected VARCHAR(50),
    importedby   VARCHAR(50),
    importedat   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    rowstotal    INTEGER NOT NULL DEFAULT 0,
    rowsimported INTEGER NOT NULL DEFAULT 0,
    rowsskipped  INTEGER NOT NULL DEFAULT 0,
    rowserror    INTEGER NOT NULL DEFAULT 0
);

INSERT INTO ledgersequence (seqname, nextvalue) VALUES
    ('RECEIPT', 1), ('NONGST', 1), ('PROFORMA', 1)
ON CONFLICT (seqname) DO NOTHING;

INSERT INTO businesssegments (businesssegmentname, segmentcode, sortorder) VALUES
    ('FSS Calculation', 'CALC', 1),
    ('FSS Consultancy', 'CONSULT', 2),
    ('Next Gen', 'NEXTGEN', 3)
ON CONFLICT (businesssegmentname) DO NOTHING;

INSERT INTO expensecategories (categoryname, issystem) VALUES
    ('NextGen Software Infrastructure', 1),
    ('Office Rent', 1),
    ('Electricity', 1),
    ('Maid / Housekeeping', 1),
    ('Internet', 1),
    ('Marketing', 1),
    ('Travel', 1),
    ('Hotel', 1),
    ('Software Subscription', 1),
    ('Consultant Fees', 1),
    ('Salaries', 1),
    ('Professional Fees', 1),
    ('Miscellaneous', 1)
ON CONFLICT (categoryname) DO NOTHING;
